#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# customize fasd
alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias v='f -e vim'       # quick opening files with vim

# start charade to integrate with pageant
if [[ "$(whence -w keychain)" != "keychain: none" ]]; then
    eval `keychain -Q --eval --quiet`
fi

# use GNU coreutils from homebrew, if available
if [[ -e /usr/local/bin/brew ]]; then
    [[ -d $(brew --prefix coreutils)/libexec/gnubin ]] && path=($(brew --prefix coreutils)/libexec/gnubin $path)
    [[ -f ~/.profile.d/brew.sh ]] && source ~/.profile.d/brew.sh
fi

# load some files from ~/.profile.d
for _PFSCRIPT in $(/usr/bin/find -L $HOME/.profile.d -type f -iname '*.sh' -or -iname '*.zsh' | LC_ALL=C sort); do
    [[ $_PFSCRIPT = *gflow.sh || $_PFSCRIPT = *multissh.sh ]] && continue
    source $_PFSCRIPT
done
unset _PFSCRIPT

# change @#%! prezto defaults
export EDITOR='vim'
export VISUAL='vim'
export LESS='-F -g -i -R -W -X'

# easily open new tabs in mvim from CLI
if [[ "$(whence -w mvim)" = "mvim: command" ]]; then
    alias tvim='mvim -p --remote-tab-silent'
fi

# enable zsh-navigation-tools
if [[ -d /usr/local/share/zsh-navigation-tools ]]; then
    fpath+=( /usr/local/share/zsh-navigation-tools )
    source /usr/local/share/zsh-navigation-tools/zsh-navigation-tools.plugin.zsh
fi

# enable online help
unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help

# make sure ~/bin in path
path=($path ~/bin)
typeset -U path
